Add iostream header and namespace std
kiwix/kiwix-tools pull request #564
Opened 2022-07-05 15:18 UTC by juuz0

Adds iostream header in src/version.h
Adds std namespace declaration in kiwix-serve.cpp
Fixes #563

2022-07-05 15:25 UTC, juuz0 commented
Needs https://github.com/kiwix/libkiwix/pull/794 to pass CI checks

2022-07-06 09:24 UTC, mgautierfr requested changes

2022-07-06 09:24 UTC, mgautierfr commented on src/server/kiwix-serve.cpp
> +using namespace std;
Please don't. Add explicit `std::` when it is needed (`std::vector`, `std::string`, ....) instead.

2022-07-06 15:21 UTC, mgautierfr requested changes

2022-07-06 15:21 UTC, mgautierfr commented on src/server/kiwix-serve.cpp
> +  /* Run std::endless (until PPID dies) */
Wrong search and replace :)

2022-07-06 15:26 UTC, juuz0 commented on src/server/kiwix-serve.cpp
> +  /* Run std::endless (until PPID dies) */
Caught out :'D

2022-07-06 15:28 UTC, juuz0 commented
The CI still fails, why?

2022-07-06 16:06 UTC, mgautierfr commented
> The CI still fails, why?

The fix on libkiwix has been merged, but the kiwix-build nightly which build the dependencies for kiwix-tools (and so build libkiwix) has not yet run. So we are still compiling kiwix-tools with yesterday master.

2022-07-06 16:06 UTC, mgautierfr approved these changes

2022-07-07 04:32 UTC, kelson42 approved these changes

2022-07-07 04:34 UTC, merged