Remove more references to kiwix-read
kiwix/kiwix-tools pull request #569
Opened 2022-07-25 20:45 UTC by legoktm

Was removed in f9ce353ad181cb3e.

2022-07-25 20:50 UTC, legoktm commented
The CI failures seem unrelated to my change?

2022-07-26 06:26 UTC, veloman-yunkan requested changes
Two more references to `kiwix-read` are also present in

- `docker/README.md`
- `format_code.sh`

2022-07-31 00:45 UTC, legoktm commented
@veloman-yunkan done!

2022-07-31 07:33 UTC, veloman-yunkan approved these changes

2022-07-31 07:45 UTC, merged