add ipv6 support
kiwix/kiwix-tools pull request #673
Opened 2024-04-20 14:30 UTC by aryanA101a

resolves #545 

depends on https://github.com/kiwix/libkiwix/pull/1074

2024-04-22 11:11 UTC, veloman-yunkan commented on src/server/kiwix-serve.cpp
> +          break;
Can't the type of the address be detected automatically?

2024-05-18 14:27 UTC, veloman-yunkan requested changes

2024-05-18 14:27 UTC, veloman-yunkan commented on docs/kiwix-serve.rst
> +  ipv6 : Accept connections from all IPv6 addresses.
"Accept connections from an IP address" is very different from "Listen for connections on an IP address"

2024-05-18 14:27 UTC, veloman-yunkan commented on src/man/kiwix-serve.1
> +ipv6 : Accept connections from all IPv6 addresses.
Same here

2024-05-18 14:27 UTC, veloman-yunkan commented on src/server/kiwix-serve.cpp
> +            << "\t-i, --address\t\tListen only on this ip address, all available ones otherwise, or specify special values to accept connections from ipv4/ipv6/all devices" << std::endl
Change to

Listen only on the specified IP address. Specify 'ipv4', 'ipv6' or 'all' to listen on all IPv4, IPv6 or both types of addresses, respectively (default: all).

2024-05-25 08:23 UTC, kelson42 commented
@aryanA101a Now that https://github.com/kiwix/libkiwix/pull/1074 is (almost) ready, we should focus on this PR. Is this PR ready for a new review? Could you please give a specific feedback to each comment of the reviewer?

2024-05-30 04:30 UTC, kelson42 commented
@aryanA101a Can we complete this PR?

2024-05-30 08:50 UTC, aryanA101a commented
I'm not sure why the build is failing. Is it due to `dpkg-buildpackage` does something different?
https://github.com/kiwix/kiwix-tools/actions/runs/9188369878/job/25571181092?pr=673#step:9:432
Perhaps it is not linking with libkiwix.so

2024-05-30 09:10 UTC, kelson42 commented
@aryanA101a This is something out of the scope of this PR. I'm more concerned about the fact that other parts of the CI (like compilation on Linux) is not triggered at all!

2024-05-30 09:40 UTC, mgautierfr commented
> I'm more concerned about the fact that other parts of the CI (like compilation on Linux) is not triggered at all!

Should be fixed by #679

2024-05-31 11:53 UTC, veloman-yunkan commented on docs/kiwix-serve.rst
> +  ipv6 : Listen for connections from all IPv6 addresses.
1. from → on
2. Make it a bulleted list (start each line with a `- `). Build (via `ninja doc`) and check the documentation to make sure that it looks nice.

2024-05-31 11:53 UTC, veloman-yunkan commented on src/man/kiwix-serve.1
> +ipv6 : Listen for connections from all IPv6 addresses.
from → on

2024-05-31 11:56 UTC, veloman-yunkan commented
Since I actually performed the proposed changes locally (in order to find out the proper formatting of documentation) I also committed them. If you are fine with them, please rebase&fix-up and we will merge this PR.

2024-06-01 08:28 UTC, kelson42 commented
@aryanA101a Please squash everything in one commit

2024-06-01 15:49 UTC, merged